[build-system]
requires = ["pybind11", "setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "python_accidental_noise_library"
version = "0.1.0"
description="A test project using pybind11 and CMake"
dynamic = ["optional-dependencies", "requires-python"]
